### ISSUE TITLE
Large queries get: evaluation exceeded backwards branches

### ISSUE THREAD

**Issue by daurnimator** [vrischmann/zig-sqlite#30]
e.g.

```
/home/daurnimator/src/zig/lib/std/mem.zig:159:5: error: evaluation exceeded 1000 backwards branches
    for (source) |s, i|
    ^
./vendor/zig-sqlite/query.zig:100:17: note: called from here
        mem.copy(u8, &parsed_query.query, &buf);
                ^
./vendor/zig-sqlite/sqlite.zig:466:93: note: called from here
    pub fn prepare(self: *Self, comptime query: []const u8) !Statement(.{}, ParsedQuery.from(query)) {
                                                                                            ^
./vendor/zig-sqlite/sqlite.zig:466:71: note: called from here
    pub fn prepare(self: *Self, comptime query: []const u8) !Statement(.{}, ParsedQuery.from(query)) {
                                                                      ^
```

**Comment by vrischmann** [comment]
it fails with small queries too, just running `zig build test` is enough.
It fails since [this zig commit](https://github.com/ziglang/zig/commit/2440c08ab02f7d7b82deb3bd4eeaafb33483307f).

**Comment by vrischmann** [comment]
repro:
```
const std = @import("std");

const sqlite = @import("sqlite");

pub fn main() anyerror!void {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const allocator = &arena.allocator;

    var db: sqlite.Db = undefined;
    try db.init(.{
        .mode = sqlite.Db.Mode{ .Memory = {} },
    });

    comptime var i: comptime_int = 0;
    inline while (i < 6) : (i += 1) {
        const query = "select id from users where id != ?{usize}";
        var stmt = try db.prepare(query);
        defer stmt.deinit();

        var iter = try stmt.iterator(usize, .{@as(usize, 3)});

        while (try iter.nextAlloc(allocator, .{})) |r| {
            _ = r;
            // std.log.info("{d} | {s}", .{ r.id, r.name });
        }
    }
}
```
any value above 5 iteration fails with:
```
/home/vincent/dev/perso/libs/zig-sqlite/query.zig:42:13: error: evaluation exceeded 1000 backwards branches
            switch (state) {
            ^
/home/vincent/dev/perso/libs/zig-sqlite/sqlite.zig:466:93: note: called from here
    pub fn prepare(self: *Self, comptime query: []const u8) !Statement(.{}, ParsedQuery.from(query)) {
                                                                                            ^
/home/vincent/dev/perso/libs/zig-sqlite/sqlite.zig:466:71: note: called from here
    pub fn prepare(self: *Self, comptime query: []const u8) !Statement(.{}, ParsedQuery.from(query)) {
                                                                      ^
./src/main.zig:5:29: note: called from here
pub fn main() anyerror!void {
                            ^
/home/vincent/dev/perso/libs/zig-sqlite/sqlite.zig:466:93: note: referenced here
    pub fn prepare(self: *Self, comptime query: []const u8) !Statement(.{}, ParsedQuery.from(query)) {
                                                                                            ^
./src/main.zig:18:34: note: referenced here
        var stmt = try db.prepare(query);
```

not sure if this change in zig is intended or if it's a regression.

**Comment by vrischmann** [comment]
I did my bisecting wrong, the first bad commit is https://github.com/ziglang/zig/commit/b11ac9c5bfb4048eb4aa561f8b3b058a76787f7e

**Comment by vrischmann** [comment]
should be fixed on master now

**Comment by daurnimator** [comment]
Doesn't it need to exist in `ParsedQuery.from`? (considering that is public)

**Comment by vrischmann** [comment]
do you mean calling `@setEvalBranchQuota` in `ParsedQuery.from` ?

**Comment by daurnimator** [comment]
> do you mean calling `@setEvalBranchQuota` in `ParsedQuery.from` ?

yes

**Comment by vrischmann** [comment]
yeah I guess that would be a better fix, although I'm wondering if there's a way to keep `ParsedQuery` private because I don't really see a use case for it outside of the statement type.
