### ISSUE TITLE
Latest version zig build failed

### ISSUE THREAD

**Issue by tocha699** [vrischmann/zig-sqlite#176]
### zig-sqlite commit

git+https://github.com/vrischmann/zig-sqlite#0155a63a7efb64da6c535ee31e92ec421712951a

### Zig version

0.14.0-dev.2605+136c5a916

### Steps to reproduce

```
C:\Codes\zig\demos\zig-sqlite-demo>zig build run
C:\Users\Administrator\AppData\Local\zig\p\12204ecfb22b7109dd3400cbdae8885e31fc653f33424bf35fe5fa21ceeadc90fcf8\build.zig:121:85: error: no field or member function named 'defaultValue' in 'builtin.Type.StructField'
        const opt = b.option(bool, field.name, "Enable " ++ field.name) orelse field.defaultValue().?;
                                                                               ~~~~~^~~~~~~~~~~~~
C:\Paths\zig\lib\std\builtin.zig:645:29: note: struct declared here
    pub const StructField = struct {
                            ^~~~~~
referenced by:
    runBuild__anon_65164: C:\Paths\zig\lib\std\Build.zig:2389:44
    dependencyInner__anon_59125: C:\Paths\zig\lib\std\Build.zig:2369:29
    8 reference(s) hidden; use '-freference-trace=10' to see all references
```

### Expected behaviour

Latest version zig build failed

**Comment by vrischmann** [comment]
It works for me on macOS and Linux, even using your specific zig version. I've tested it just now and the `defaultValue` definitely exists, something is wrong with your zig installation.

I can suggest this:
* remove all your cache directories and try again
* make sure your lib directory (`C:/Paths/zig/lib`) is up to date. Maybe you're using a recent binary with an old zig lib dir. You can run `zig env` to check which `lib_dir` is used

**Comment by tocha699** [comment]
I used the Windows version. I switched to the stable version but it still didn't work. It prompted the same error. It should be a bug in the Zig Windows version.

**Comment by vrischmann** [comment]
Yeah it won't work with zig 0.13.0, this stuff has only beed added relatively recently to the master branch.

I'll try to find some time to test on Windows.

**Comment by scripturial** [comment]
Yea, I am getting this problem on MacOS (latest), with Zig 0.13. What is the workaround? What is the last known working commit for 0.13?

I wonder if perhaps this project could add a tag, i.e. 0.13-LATEST or something like that?

```
/Users/scripturial/.cache/zig/p/1220bbf36166a56f03ca55c2f455f70cdb3dd5f8dca1f7c78e57d9402add9635b2b9/build.zig:121:85: error: no field or member function named 'defaultValue' in 'builtin.Type.StructField'
        const opt = b.option(bool, field.name, "Enable " ++ field.name) orelse field.defaultValue().?;
                                                                               ~~~~~^~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/builtin.zig:344:29: note: struct declared here
    pub const StructField = struct {
                            ^~~~~~
referenced by:
    runBuild__anon_16155: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/Build.zig:2117:37
    dependencyInner__anon_14832: /opt/homebrew/Cellar/zig/0.13.0/lib/zig/std/Build.zig:2097:29
    remaining reference traces hidden; use '-freference-trace' to see all reference traces
```

**Comment by scripturial** [comment]
I've just tested doing `zig fetch --save git+https://github.com/vrischmann/zig-sqlite#d1e3865115aa5f27c6c75e8061277e898d155210` to wind back to an older version, and it works now. So something broke for 0.13 (on Mac at least) in the more recent versions.

**Comment by vrischmann** [comment]
Yours is not the same issue, zig 0.13.0 is explicitly not supported, zig-sqlite only tracks master for now. I have plans to introduce a branch for stable zig releases but there's nothing yet.

Your commit doesn't work with zig 0.13.0 though. If I checkout d1e3865115aa5f27c6c75e8061277e898d155210 and run `zig build test` it fails with error like these:
```
/Users/vincent/.zvm/0.13.0/lib/std/builtin.zig:256:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
query.zig:154:53: note: called from here
                                break :blk ParseType(type_info_string);
                                           ~~~~~~~~~^~~~~~~~~~~~~~~~~~
query.zig:34:29: note: called from here
        const result = parse();
                       ~~~~~^~
query.zig:210:14: error: no field named 'int' in union 'builtin.Type'
            .int = std.builtin.Type.Int{
             ^~~
/Users/vincent/.zvm/0.13.0/lib/std/builtin.zig:256:18: note: union declared here
pub const Type = union(enum) {
                 ^~~~~
query.zig:154:53: note: called from here
                                break :blk ParseType(type_info_string);
                                           ~~~~~~~~~^~~~~~~~~~~~~~~~~~
query.zig:34:29: note: called from here
        const result = parse();
```

How are you testing that it works ?

**Comment by vrischmann** [comment]
As far as I can tell 7f4be7d30b126affb66b390c7825addb1c3506bd is the latest commit that works with zig 0.13.0

**Comment by vrischmann** [comment]
I've created the branch `zig-0.13.0` which you can use to have a version that will stay compatible with zig 0.13.0

**Comment by scripturial** [comment]
Yes, I just worked out that the earlier commit fixed this error, but had another error. I can confirm that the branch works great with 0.13. Thanks! 

I did a zig fetch with this and it definitely creates a sqlite file without problems:

```
git+https://github.com/vrischmann/zig-sqlite?ref=zig-0.13.0#7f4be7d30b126affb66b390c7825addb1c3506bd
```
